version: 1
disable_existing_loggers: false


formatters:
    standard:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout
    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: Splunk_data.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
root:
    level: NOTSET
    handlers: [console, debug_file_handler]
    propagate: yes

loggers:
    <module>:
        level: DEBUG
        handlers: [console, debug_file_handler]
        propagate: no

    <module.x>:
        level: DEBUG
        handlers: [debug_file_handler]
        propagate: yes

cleanup:
  days_to_delete: 10